# Generated by Django 4.2 on 2023-04-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('Name_eng', models.CharField(max_length=200, verbose_name='name_eng')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Day', models.IntegerField(verbose_name='Day')),
                ('Was_more_fourty', models.BooleanField(default=False, verbose_name='Was_more_fourty')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('Active_a', models.FloatField(default=100, verbose_name='active_a')),
                ('Active_a_pred', models.FloatField(default=100, verbose_name='active_a')),
                ('Active_b', models.FloatField(default=100, verbose_name='active_b')),
                ('Active_b_pred', models.FloatField(default=100, verbose_name='active_b')),
                ('Active_c', models.FloatField(default=100, verbose_name='active_c')),
                ('Active_c_pred', models.FloatField(default=100, verbose_name='active_c')),
                ('Education', models.IntegerField(default=0, verbose_name='education')),
                ('Day', models.IntegerField(default=1, verbose_name='day')),
                ('History', models.CharField(default='[300]', max_length=400, verbose_name='history')),
                ('Mortgage_count', models.IntegerField(default=0, verbose_name='mortgage_count')),
                ('Further_mortgage', models.IntegerField(default=0, verbose_name='further_mortgage')),
                ('Now_mortgage', models.IntegerField(default=0, verbose_name='now_mortgage')),
                ('Active_a_historical', models.FloatField(default=100, verbose_name='active_a_historical')),
                ('Active_b_historical', models.FloatField(default=100, verbose_name='active_b_historical')),
                ('Active_c_historical', models.FloatField(default=100, verbose_name='active_c_historical')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(verbose_name='day')),
                ('ActA_increase', models.CharField(default='обработка', max_length=10, null=True, verbose_name='actAinc')),
                ('ActB_increase', models.CharField(default='обработка', max_length=10, null=True, verbose_name='actBinc')),
                ('ActC_increase', models.CharField(default='обработка', max_length=10, null=True, verbose_name='actCinc')),
                ('Money_in', models.FloatField(null=True, verbose_name='money_in')),
                ('Money_out', models.FloatField(null=True, verbose_name='money_in')),
                ('Not_chosen_number', models.IntegerField(default=0, verbose_name='not_chosen_number')),
                ('Name1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_a', to='Game.active')),
                ('Name2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_b', to='Game.active')),
                ('Name3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_c', to='Game.active')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.player')),
            ],
        ),
    ]
