# Generated by Django 4.2 on 2023-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='CurrentGameID',
            field=models.IntegerField(default=0, verbose_name='game_id'),
        ),
    ]
